name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    if: false # Disabled as it takes too much time, more than half an hour
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: autoreconf -i
      - run: ./configure
      - run: make all -j3
      - run: make dist
      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: advmame    
  build-win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: mingw-w64-i686-gcc mingw-w64-i686-clang mingw-w64-i686-pkg-config mingw-w64-i686-SDL2 autoconf automake make zip
      - run: autoreconf -i --include=/mingw32/share/aclocal
      - run: CC=clang CXX=clang++ ./configure.windows
      - run: make all -j3
      - uses: actions/upload-artifact@v4
        with:
          name: win32
          path: |
           advmame.exe
           advance/svgalib/svgawin/install/svgawin.exe
           advmenu.exe
           advmess.exe
           
           
                
 
